### ISSUE TITLE
HANDLE NOT FOUND when registering dataset

### ISSUE THREAD

**Issue by zcc39r** [datacite/mds#333] opened 2018-04-09 07:45 UTC
Unable to register dataset using prefix 10.18435. Other prefixes (including test) work fine.
![img_09042018_103247_0](https://user-images.githubusercontent.com/17593292/38485537-c52c182a-3be2-11e8-8dc1-2bf95eeee7b0.png)

**Comment by mfenner** [comment] 2018-04-09 08:05
What data center was used for login? This prefix is associated with SPBPU.SUIMBL. You can also send a message to support@datacite.org for these kinds of issues.

**Comment by zcc39r** [comment] 2018-04-09 08:16
Data center was SPBPU.SUIMBL.

**Comment by richardhallett** [comment] 2018-04-09 17:58
We've investigated the issue, it turns out not to be a bug but an incorrectly assigned prefix that was already assigned to another institution.

I have removed this prefix and given you a new one of 10.18127 you should hopefully not have any problems with this one.

**Closed by richardhallett** 2018-04-09 17:58 UTC
Labels: bug, development

**Comment by zcc39r** [comment] 2018-04-09 18:56
Thank you Richard! I obtained that prefix via DOI Fabrica. So if it was incorrectly assigned then there is probably another bug exists in the assignment procedure...

**Comment by mfenner** [comment] 2018-04-09 19:18
As @richardhallett said, the underlying problem was not a bug, but a human error. So there is nothing else to do. 

Let us know if you see any issues with the new prefix.
